tasks:
  - init: |
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-pycharm-c
      # sudo docker pull registry.jetbrains.team/p/prj/containers/projector-pycharm-u
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains; sudo -R chmod 777 .jetbrains
      # Community Edition
      sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-pycharm/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-pycharm-c
ports:
  - port: 8887
    visibility: private
    onOpen: open-browser
