tasks:
  - init: |
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-pycharm-c
      # sudo docker pull registry.jetbrains.team/p/prj/containers/projector-pycharm-u
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      # Community Edition
      sudo docker run --rm -p 8887:8887 -v /workspace/uarizona-salary-app/.jetbrains:/home/projector-user -d registry.jetbrains.team/p/prj/containers/projector-pycharm-c sudo chmod -R 777 /home/projector-user
ports:
  - port: 8887
    visibility: private
    onOpen: open-browser
