name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "sapp4ua"
          heroku_email: "astro.chun@gmail.com"
